


obj_dir/Vlsa : lsa.v vmain.cpp sram.h
	verilator --cc lsa.v --exe vforever.cpp 
	make -C obj_dir/ -f Vlsa.mk

lsa.v : lsa.cdl
	cdl --verilog lsa.v --include-dir .  lsa.cdl

clean :
	rm -rf obj_dir
	rm -f test.vcd


